### ISSUE TITLE
element-ui <el-table-column prop='变量'>

### ISSUE THREAD

**Issue by irenetang1993** [yeyuqiudeng/vue-bel-table#1]
<el-table :data="tableData">
  <el-table-column :prop="nameVariable"></el-table-column>
</el-table>

data() {
  return {
    tableData:[{
      name: 'irene'
    }],
    nameVariable: 'name'
  }
}

我现在也想再封装<el-table>，但是遇到了一个问题，当prop指定为一个变量的时候，列的数据就不显示了

**Comment by HeftyKoo** [comment]
这样写就好了`<el-table-column :prop='变量'>`

**Comment by irenetang1993** [comment]
想请您看看这个问题，非常感谢！
https://segmentfault.com/q/1010000009130479

**Comment by rayunstop** [comment]
您好，我想问下，比如我想自定义el-table的sort-method,
<el-table-column prop="age" label="Age" sortable :sort-method=test width="180">
这样是可以的。

但是我们自己定义列的属性:
attr = {label: "Age", sortable: true, 'sort-method': this.test}
这种是不行的，请问下这种情况应该怎么写？
