### ISSUE TITLE
el-table 属性写法问题

### ISSUE THREAD

**Issue by rayunstop** [yeyuqiudeng/vue-bel-table#2]
您好，我想问下，比如我想自定义el-table的sort-method,
<el-table-column prop="age" label="Age" sortable ：sort-method=test width="180">
这样是可以的。

但是我们自己定义列的属性:
attr = {label: "Age", sortable: true, 'sort-method': this.test}
这种是不行的，请问下这种情况应该怎么写？

**Comment by HeftyKoo** [comment]
目前没有兼容这种写法，要写成驼峰式 `sortMethod `
