### ISSUE TITLE
Invalid prop: type check failed for prop "configs". Expected Object, got Undefined.

### ISSUE THREAD

**Issue by ShawshankLin** [yeyuqiudeng/vue-bel-table#3]
![qq 20180226164603](https://user-images.githubusercontent.com/16248686/36660867-97b51e12-1b14-11e8-89da-909e4701b39d.png)

当初始化的时候，，如果是由prop传入数据对象的话，，会有延时就会报这个错

**Comment by HeftyKoo** [comment]
不是很明白，可以给个使用的例子吗？

**Comment by ShawshankLin** [comment]
就是我的页面通过prop拿到父组件传过来的id，，然后异步去获取远程数据，，然后在绑定到:configs的变量进去，，这样的话，，在初始化页面的时候变量的对象是空的，就会报这个错，等我拿到数据了，就正常显示了

**Comment by ShawshankLin** [comment]
所以的话就会报一个undefined的错误了，，因为页面初始化的时候没有传入对象

**Comment by HeftyKoo** [comment]
@ShawshankLin 可以先定义好初始的 `config` 值，后续赋值即可

**Comment by ShawshankLin** [comment]
我试过的，，比如我这样先初始了
tableConfig: {
          table: {
            attr: {
              data: this.tableData
            }
          },
          columns: [
            {
              attr: {
                type: 'selection',
                width: 80,
                align: 'center'
              }
            },
            {
              attr: {
                prop: 'date',
                label: '日期',
                minWidth: 180,
                scopedSlot: 'date'
              }
            },
            {
              attr: {
                prop: 'name',
                label: '姓名',
                minWidth: 180
              }
            },
            {
              attr: {
                prop: 'address',
                label: '地址',
                minWidth: 180
              }
            }
          ]
        }
      }

但是重新赋值上去table是没有数据的，，然后我去掉columns里面的又会报另一个错
![qq 20180227210733](https://user-images.githubusercontent.com/16248686/36730424-51bca080-1c02-11e8-9c18-b85689b41f27.png)

**Comment by ShawshankLin** [comment]
噢没事了，，，是可以的，，刚又试了下是好了
